# Generated by Django 4.2.10 on 2024-03-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='main.product'),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='notes',
        ),
        migrations.CreateModel(
            name='SCINote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researcher_names', models.TextField()),
                ('institution_name', models.TextField(blank=True)),
                ('notes_content', models.TextField()),
                ('citations', models.TextField(blank=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='notes', to='main.scinote'),
        ),
    ]
