# Generated by Django 5.0.2 on 2024-04-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_id',
        ),
    ]
