# Generated by Django 5.0.2 on 2024-04-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_id',
            field=models.TextField(blank=True),
        ),
    ]
