# Generated by Django 5.0.2 on 2024-04-13 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_imagemodel_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='title',
        ),
    ]
