# Generated by Django 4.2.10 on 2024-04-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_profile_color_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
